spring:
  application:
    name: basket-services

server:
     port: 9000
     address: localhost

logging:
  levels:
    org.springframework.boot.env.PropertySourcesLoader: TRACE
    org.springframework.web: DEBUG
    org.springframework.cloud: DEBUG

eureka:
  instance:
    hostname: localhost
  client:
    healthcheck:
      enabled: true