eureka:
  image: justindav1s/eureka
  ports:
   - "8761:8761"

config:
  image: justindav1s/config
  ports:
   - "8888:8888"
  links:
   - eureka

product:
  image: justindav1s/product
  ports:
     - "9005:9005"
  links:
   - eureka
   - config
