server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: true

ribbon:
  eureka:
    enabled: true