server:
  port: 9999
  contextPath: /auth


eureka:
  client:
    registryFetchIntervalSeconds: 3
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5

spring.cloud.config.discovery.enabled: true

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

ribbon:
  eureka:
    enabled: true

security:
  user:
    name: justin
    password: toffee


logging:
  level:
    org.springframework.security: DEBUG