server:
  port: 8080

eureka:
  client:
    registryFetchIntervalSeconds: 3
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5

spring.cloud.config.discovery.enabled: true

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

ribbon:
  eureka:
    enabled: true

spring:
  oauth2:
    resource:
      userInfoUri: http://${DOCKER_MACHINE_ADDR}:9080/auth/realms/master/protocol/openid-connect/userinfo

#userInfoUri: http://authserver:9999/auth/user

zuul:
  prefix: /api
  ignoredServices: '*'
  routes:
    basket:
      serviceId: basket
      path: /basket/**
      stripPrefix: false
      retryable: true
    product:
      serviceId: product
      path: /product/**
      stripPrefix: false
      retryable: true