apiVersion: v1
kind: Service
metadata:
  name: config
  labels:
    name: config

spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  # the IP address for NodePort will be your minion node's IP address, not the cluster IP
  # in my case its 10.245.1.3
  type: NodePort
  ports:
    # the port that this service should serve on
  - port: 8888
  selector:
    name: config
