apiVersion: v1
kind: ReplicationController
metadata:
  name: config
  labels:
    name: config
spec:
  replicas: 1
  selector:
    name: config
  template:
    metadata:
      labels:
        name: config
    spec:
      containers:
      - name: config
        image: justindav1s/config
        ports:
        - containerPort: 8888
