apiVersion: v1
kind: ReplicationController
metadata:
  name: product
  labels:
    name: product
spec:
  replicas: 2
  selector:
    name: product
  template:
    metadata:
      labels:
        name: product
    spec:
      containers:
      - name: product
        image: justindav1s/product
        ports:
        - containerPort: 8080
