product:
  image: justindav1s/product
  ports:
     - "8081:8080"
  links:
   - eureka
   - config
   - mongo

product:
  image: justindav1s/product
  ports:
     - "8083:8080"
  links:
   - eureka
   - config
   - mongo