product:
  image: justindav1s/product
  ports:
     - "8081:8080"
  external_links:
   - infra_eureka_1:eureka
   - infra_config_1:config
   - data_mongo_1:mongo

basket:
  image: justindav1s/basket
  ports:
     - "8083:8080"
  external_links:
   - infra_eureka_1:eureka
   - infra_config_1:config
   - data_mongo_1:mongo