zuul:
  image: justindav1s/zuul
  ports:
   - "8080:8080"
  external_links:
   - infra_eureka_1:eureka
   - infra_config_1:config

keycloakproxy:
  image: justindav1s/keycloak_proxy
  ports:
   - "7080:8080"
  links:
   - zuul

varnish:
  image: justindav1s/varnish
  ports:
   - "80:80"
  links:
   - keycloakproxy
